### ISSUE TITLE
Failed to import @mdx-js/mdx

### ISSUE THREAD

**Issue by amatiasq** [alephjs/esm.sh#167] opened 2021-09-22 11:36 UTC
## Failing module

- **GitHub**: https://github.com/mdx-js/mdx
- **npm**: https://www.npmjs.com/package/@mdx-js/mdx

```js
import 'https://esm.sh/@mdx-js/mdx'
```

## Error message

After running

```
deno eval 'import "https://esm.sh/@mdx-js/mdx"'
```

I get this:

```
error: Uncaught TypeError: (0 , N.default) is not a function
    at https://cdn.esm.sh/v53/@babel/helper-function-name@7.15.4/deno/helper-function-name.js:2:1429
    at https://cdn.esm.sh/v53/@babel/helper-function-name@7.15.4/deno/helper-function-name.js:2:640
    at https://cdn.esm.sh/v53/@babel/helper-function-name@7.15.4/deno/helper-function-name.js:26:1406
```

## Additional info

- **esm.sh version**: v53
- **Deno version**: 1.14.0

## Analysis

After analyzing the issue I found out it is because `helper-function-name.js` starts with [this import](https://github.com/babel/babel/blob/main/packages/babel-helper-function-name/src/index.ts#L2):

```ts
import template from "@babel/template";
// below at line 21...
const buildPropertyMethodAssignmentWrapper = template(`... `)
```

Which is [transpiled](https://cdn.esm.sh/v53/@babel/helper-function-name@7.15.4/deno/helper-function-name.js) as

```js
import ___babel_template$ from '/v53/@babel/template@7.15.4/deno/template.js';
// ...
var N = ___babel_template$;
// ...
j = (0, N.default)(`...`)
```

So you can see we're importing the default export but then again we try to access it's default property for some reason.

**Comment by amatiasq** [comment] 2021-09-22 14:26
Referenced from https://github.com/mdx-js/mdx/discussions/1674

**Comment by ije** [comment] 2021-09-22 17:12
@amatiasq thanks for the details, i will look into it!

**Comment by talentlessguy** [comment] 2021-09-25 09:55
duplicate of #142

**Closed by talentlessguy** 2021-09-25 09:55 UTC
Labels: bug

**Comment by amatiasq** [comment] 2021-09-25 11:54
@talentlessguy I think the analysis is worth copying too

**Comment by ije** [comment] 2021-09-25 11:57
@amatiasq yes, thanks for the details
